{% set plugin_version = environ['PLUGIN_VERSION'].lstrip('v') %}

package:
  name: openmm-cpp-forces
  version: {{ plugin_version }}

source:
  git_url: ../../..

build:
  number: 0

requirements:
  build:
    - python
    - swig <4.1
    - openmm >=8.1
    - {{ compiler('cxx') }}
    - cmake
    - make
    - setuptools
    - pip
    - numpy >=1.19
  host:
    - python
    - openmm >=8.1
  run:
    - python
    - {{ pin_compatible('openmm', max_pin='x.x') }}

test:
  imports:
    - openmmcppforces

about:
  home: https://github.com/RedesignScience/openmm-cpp-forces
  summary: Platform-agnostic OpenMM Forces
  license: MIT
  license_file: LICENSE.md
  doc_url: https://RedesignScience.github.io/openmm-cpp-forces
  dev_url: https://github.com/RedesignScience/openmm-cpp-forces

extra:
  recipe-maintainers:
    - RedesignScience
