name: Docs

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    name: Build and Deploy to GitHub Pages
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: "3.11"
            openmm-version: "8.1"
            gcc-version: "13"

    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Additional info about the build"
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: "Install Micromamba"
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/build-docs.yml
          environment-name: docs
          create-args: >-
            python=${{ matrix.python-version }}
            gxx_linux-64=${{ matrix.gcc-version }}
            openmm=${{ matrix.openmm-version }}

      - name: "List conda packages"
        shell: bash -l {0}
        run: micromamba list

      - name: "Configure"
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: "Build package"
        shell: bash -l {0}
        run: |
          cd build
          make -j2 install
          make -j2 PythonWrapper
          pip install --no-deps -e python/

      - name: "Build docs"
        shell: bash -l {0}
        run: |
          sphinx-build ./docs ./html

      - name: "Deploy docs to GitHub Pages"
        shell: bash -l {0}
        run: |
          git reset --hard HEAD
          set -x
          echo "::group::Push page to gh-pages branch"
          git config user.name "$(git show --format=%an -s)"
          git config user.email "$(git show --format=%ae -s)"
          git fetch origin
          git switch gh-pages
          rsync -va --delete-excluded html/ docs/
          touch docs/.nojekyll
          git add -f docs/*
          git add -f docs/.nojekyll
          git commit -m "Docs from $GITHUB_REF $GITHUB_SHA" || echo "Branch is up to date"
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "Deployment is deactivated in pull requests"
          else
            git push -f origin gh-pages
          fi
          echo "::endgroup::"
