name: Linux

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weely tests run on Sundays at 4 AM UTC (12 AM EST):
    - cron: "0 4 * * 0"

jobs:
  unix:
    runs-on: ubuntu-20.04
    name: Linux (Python ${{ matrix.python-version }}, OpenMM ${{ matrix.openmm-version }}, GCC ${{ matrix.gcc-version }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # Oldest supported versions
          - python-version: "3.9"
            openmm-version: "8.1"
            gcc-version: "9.4"

          # Latest supported versions
          - python-version: "3.11"
            openmm-version: "8.1"
            gcc-version: "13.2"

    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Update the conda enviroment file"
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '@'
          tokenSuffix: '@'
          files: devtools/conda-envs/build-ubuntu-20.04.yml
        env:
          GCC_VERSION: ${{ matrix.gcc-version }}
          OPENMM_VERSION: ${{ matrix.openmm-version }}

      - uses: conda-incubator/setup-miniconda@v2
        name: "Install dependencies with conda"
        with:
          activate-environment: build
          environment-file: devtools/conda-envs/build-ubuntu-20.04.yml
          python-version: ${{ matrix.python-version }}

      - name: "List conda packages"
        shell: bash -l {0}
        run: conda list

      - name: "Configure"
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: "Build"
        shell: bash -l {0}
        run: |
          cd build
          make -j2 install
          make -j2 PythonWrapper
          pip install --no-deps -e python/

      - name: "List plugins"
        shell: bash -l {0}
        run: |
          python -c "import openmm as mm; print('---Loaded---', *mm.pluginLoadedLibNames, '---Failed---', *mm.Platform.getPluginLoadFailures(), sep='\n')"

      - name: "Run C++ test"
        shell: bash -l {0}
        run: |
          cd build
          ctest --output-on-failure

      - name: "Run Python test"
        shell: bash -l {0}
        run: |
          cd build/python
          pytest
