name: MacOS

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weely tests run on Sundays at 4 AM UTC (12 AM EST):
    - cron: "0 4 * * 0"

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }}, OpenMM ${{ matrix.openmm-version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            python-version: "3.9"
            openmm-version: "8.1"

    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Additional info about the build"
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: "Install Micromamba"
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/build-${{ matrix.os }}.yml
          environment-name: build
          create-args: >-
            python=${{ matrix.python-version }}
            openmm=${{ matrix.openmm-version }}

      - name: "List conda packages"
        shell: bash -l {0}
        run: micromamba list

      - name: "Configure"
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: "Build"
        shell: bash -l {0}
        run: |
          cd build
          make -j2 install
          make -j2 PythonWrapper
          pip install --no-deps -e python/

      - name: "Run C++ test"
        shell: bash -l {0}
        run: |
          cd build
          ctest --output-on-failure

      - name: "Run Python test"
        shell: bash -l {0}
        run: |
          cd build/python
          pytest
